package io.github.mayachen350.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import nl.adaptivity.xmlutil.serialization.XmlElement

// WARNING: CLASSES GENERATED BY AI

@Serializable
@SerialName("lfm")
data class LfmResponse(
    @XmlElement(true) val status: String,
    @XmlElement(true) val recenttracks: RecentTracks
)

@Serializable
data class RecentTracks(
    @XmlElement(true) val user: String,
    @XmlElement(true) val page: Int,
    @XmlElement(true) val perPage: Int,
    @XmlElement(true) val totalPages: Int,
    @XmlElement(true) val total: Int,
    @XmlElement(true) val track: Track
)

@Serializable
data class Track(
    @XmlElement(true) val artist: Artist,
    @XmlElement(true) val name: String,
    @XmlElement(true) val streamable: Int,
    @XmlElement(true) val mbid: String? = null,
    @XmlElement(true) val album: Album,
    @XmlElement(true) val url: String,
    @XmlElement(true) val image: List<Image>,
    @XmlElement(true) val date: Date,
    @XmlElement(false) val nowplaying: Boolean?
)

@Serializable
data class Artist(
    @XmlElement(true) val mbid: String? = null,
    @XmlElement(true) val value: String // text content
)

@Serializable
data class Album(
    @XmlElement(true) val mbid: String,
    @XmlElement(true) val value: String
)

@Serializable
data class Image(
    @XmlElement(true) val size: String,
    @XmlElement(true) val value: String
)

@Serializable
data class Date(
    @XmlElement(true) val uts: Long,
    @XmlElement(true) val value: String
)
