name: main
run-name: Compile scss outside of the repository
on: [push]
jobs:
  scss_compilation:
    runs-on: ubuntu-latest
    steps:
      - name: install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install sass
        run: brew install sass/sass/sass
      - name: compile scss to css
        run: sass ${{ github.workspace }}/styles/scss/pages/home/main.scss ${{ github.workspace }}/styles/css/main.css
