on:
  push:
    branches:
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Compile CSS from SCSS files
        run: touch styles/css/main.css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: ./styles/scss/pages/home/main.scss
          destination: ./styles/css/main.css
